knpu_oauth2_client:
  clients:
    # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration

    google:
      type: google
      client_id: "%env(GOOGLE_CLIENT)%"
      client_secret: "%env(GOOGLE_SECRET)%"
      redirect_route: api.oauth_check
      redirect_params:
        service: google
