controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api.auth.oauth_check:
    path: /api/auth/check/{service}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
